In [22]:
import numpy as np

def ridge_inverse(X: np.ndarray, lambda_: float) -> np.ndarray:
    """
    Возвращает обратную матрицу для Ridge регрессии:
    (X^T X + lambda * I)^-1
    """
    return np.linalg.inv(((X.T).dot(X) + lambda_ * np.eye(len(X[0]))))

print(ridge_inverse(np.array([[1, 2, 3], [2, 3, 4], [1,3,6]]), 1.4))


[[ 0.44878945 -0.20339873 -0.00492094]
 [-0.20339873  0.47230059 -0.217068  ]
 [-0.00492094 -0.217068    0.14259782]]


In [23]:
# Представим обычную матрицу данных X.
# Она может быть чем угодно — например, измерения каких-то объектов.
# Специально возьмём два очень похожих столбца, чтобы показать проблему.

X = np.array(
    [
        [1, 2],
        [2, 4],
        [3, 6],
    ]
)

# Эти два столбца линейно зависимы (второй = первый * 2),
# поэтому матрица X^T X плохо обращается.

# Попробуем получить обратную матрицу при разных значениях λ
for lambda_ in [0, 0.1, 0.5, 1]:
    try:
        inv_matrix = ridge_inverse(X, lambda_)
        print(f"\nλ = {lambda_}")
        print(inv_matrix)
    except np.linalg.LinAlgError:
        print(f"\nλ = {lambda_}: матрица не обратима")

### Output:
# λ = 0: матрица не обратима

# λ = 0.1
# [[ 8.00285307 -3.99429387]
#  [-3.99429387  2.01141227]]

# λ = 0.5
# [[ 1.60283688 -0.79432624]
#  [-0.79432624  0.41134752]]

# λ = 1
# [[ 0.8028169  -0.3943662 ]
#  [-0.3943662   0.21126761]]

# Как только добавляем хоть маленькую λ, матрица становится обратимой.
# При увеличении λ обратная матрица становится более «спокойной» и стабильной.


λ = 0: матрица не обратима

λ = 0.1
[[ 8.00285307 -3.99429387]
 [-3.99429387  2.01141227]]

λ = 0.5
[[ 1.60283688 -0.79432624]
 [-0.79432624  0.41134752]]

λ = 1
[[ 0.8028169  -0.3943662 ]
 [-0.3943662   0.21126761]]
